### ISSUE TITLE
example doc_classification_multilable throws exception "TypeError: cannot perform reduce with flexible type"

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#148]
Just run the example file `doc_classification_multilable.py` unchanged and after a while during training (at about 10% of epoch 1) when evaluating the following exception is thrown:

```
TypeError: cannot perform reduce with flexible type
```

FARM (almost latest) master commit 41644de7a0b8331b6d1ba1aeca9c77431509b4dc
transformers version: 2.1.1
numpy version: 1.17.2

Here is the complete stack trace:
```
${PYTHONENVHOME}/lib/python3.6/site-packages/numpy/lib/arraysetops.py:564: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
Traceback (most recent call last):
  File "doc_classification_multilabel.py", line 97, in <module>
    model = trainer.train(model)
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/farm-0.3.1-py3.6.egg/farm/train.py", line 163, in train
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/farm-0.3.1-py3.6.egg/farm/eval.py", line 138, in eval
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1886, in classification_report
    sample_weight=sample_weight)
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1421, in precision_recall_fscore_support
    labels=labels, samplewise=samplewise)
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 457, in multilabel_confusion_matrix
    if np.max(labels) > np.max(present_labels):
  File "<__array_function__ internals>", line 6, in amax
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2621, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "${PYTHONENVHOME}/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: cannot perform reduce with flexible type
```

**Comment by tholor** [comment]
Hi @johann-petrak, 

I was able to reproduce the issue. It seems to be a new issue with the classification_report that is called during evaluation after the first 500 steps. Might be related to the changes introduced by 432ffb136a7c260b883e55c6c134a7e49ddaf53c or f6734cb88cb29a872cbe6dcc2ba7cbf81855cd50. I will investigate this.
