### ISSUE TITLE
Model name 'distilbert-base-german-cased' was not found in model name list

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#228]
Training starts of really well but then i get the following error. Please could you help ?

**Error message**

`Traceback (most recent call last):
  File "path_to_src/vitenv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 133, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "path_to_src/vitenv/lib/python3.7/site-packages/transformers/file_utils.py", line 182, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file distilbert-base-german-cased not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_src/bert.py", line 107, in <module>
    doc_regression()
  File "path_to_src/bert.py", line 59, in doc_regression
    language_model = LanguageModel.load(lang_model)
  File "path_to_src/vitenv/lib/python3.7/site-packages/farm/modeling/language_model.py", line 93, in load
    language_model = cls.subclasses["Bert"].load(pretrained_model_name_or_path, **kwargs)
  File "path_to_src/vitenv/lib/python3.7/site-packages/farm/modeling/language_model.py", line 273, in load
    bert.model = BertModel.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "path_to_src/vitenv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "path_to_src/vitenv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 145, in from_pretrained
    raise EnvironmentError(msg)
OSError: Model name 'distilbert-base-german-cased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'distilbert-base-german-cased' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
`

Here is my model: distilbert-base-german-cased
Here is my tokenizer: bert-base-german-cased

**System:**
 - OS: MAC OS
 - CPU:
 - FARM version: 0.3.2

**Comment by tholor** [comment]
Seems like a version thing to me. There were a couple of fixes within the transformers repo to load models remotely. Could you test installing the latest versions? 
```
pip uninstall farm
pip unstinstall transformers
cd FARM
pip install -e .
```

**Comment by zolekode** [comment]
Yes, you are right, most errors are coming from the versions. I now installed Transformers and then FARM directly from github. The current issue is resolved :) thanks.
