### ISSUE TITLE
error when having 1 worker to preprocess the dataset

### ISSUE THREAD

**Issue by ahmednasserswe** [deepset-ai/FARM#238]
I get the following error when I run a question answering with Farm. Happens after the data preprocessing starts. I am running on colab which gives only 1 worker for this process. When I run on AWS with multiple workers available, I don't receive the error message 
```
02/05/2020 11:26:01 - INFO - numexpr.utils -   NumExpr defaulting to 2 threads.
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/farm/data_handler/data_silo.py", line 111, in _dataset_from_chunk
    dataset = processor.dataset_from_dicts(dicts=dicts, indices=indices)
  File "/usr/local/lib/python3.6/dist-packages/farm/data_handler/processor.py", line 894, in dataset_from_dicts
    self._featurize_samples()
  File "/usr/local/lib/python3.6/dist-packages/farm/data_handler/processor.py", line 283, in _featurize_samples
    sample.features = self._sample_to_features(sample=sample)
  File "/usr/local/lib/python3.6/dist-packages/farm/data_handler/processor.py", line 1000, in _sample_to_features
    max_seq_len=self.max_seq_len)
  File "/usr/local/lib/python3.6/dist-packages/farm/data_handler/input_features.py", line 361, in sample_to_features_squad
    seq_2_start_t = segment_ids.index(1)
ValueError: 1 is not in list
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-4-95d6e10bc26a> in <module>()
----> 1 question_answering()

4 frames
/usr/lib/python3.6/multiprocessing/pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

ValueError: 1 is not in list```

**Comment by tholor** [comment]
Seems related to https://github.com/deepset-ai/FARM/issues/208 . Are you training a roberta model? Do you have the latest FARM version installed?

**Comment by ahmednasserswe** [comment]
latest version - using `xlm-roberta-base`

**Comment by tholor** [comment]
@brandenchan can you please try to replicate and see if this is related to your work in #216 ?

**Comment by brandenchan** [comment]
Hey Ahmed, sorry it took so long to get back to you. I've opened a pull request #240  that should solve this issue. Could you try it out and let me know if it works?
