### ISSUE TITLE
Can not load BERT-Model

### ISSUE THREAD

**Issue by TKueng** [deepset-ai/FARM#275]
Hello everyone 
I'm a Masterstudent at the university of St. Gallen and currently working on my Master-Thesis. I'm developing a chatbot for argumentative learning with the RASA Framework and the German BERT-Model which is provided by FARM. The BERT Model was trained with hyperparameter by a former Student and already worked in a previous (Slack)-chatbot version. But when I try to load the model, the following error occurs: 

`  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\__main__.py", line 33, in <module>
    main()
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\__main__.py", line 29, in main
    main_from_args(cmdline_args)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\__main__.py", line 20, in main_from_args
    args.ssl_password,
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\endpoint.py", line 116, in run
    app = create_app(action_package_name, cors_origins=cors_origins)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\endpoint.py", line 68, in create_app
    executor.register_package(action_package_name)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\executor.py", line 222, in register_package
    self.register_action(action)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\executor.py", line 157, in register_action
    action = action()
  File "C:\Users\tobia\OneDrive\Desktop\arguebot_test\actions.py", line 15, in __init__
    self.model = Inferencer.load("C:\\Users\\tobia\\OneDrive\\Desktop\\arguebot_test\\Model")
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\infer.py", line 133, in load
    model = AdaptiveModel.load(model_name_or_path, device, strict=strict)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\adaptive_model.py", line 125, in load
    language_model = LanguageModel.load(load_dir)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\language_model.py", line 108, in load
    language_model = cls.subclasses[config["name"]].load(pretrained_model_name_or_path)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\language_model.py", line 323, in load
    bert.model = BertModel.from_pretrained(farm_lm_model, config=bert_config, **kwargs)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modeling_utils.py", line 414, in from_pretrained
    elif os.path.isfile(pretrained_model_name_or_path) or is_remote_url(pretrained_model_name_or_path):
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\file_utils.py", line 143, in is_remote_url
    parsed = urlparse(url_or_filename)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\urllib\parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\urllib\parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\urllib\parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\urllib\parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'WindowsPath' object has no attribute 'decode'`

Any suggestions what could cause this error. Were there any changes in the framework that could provoke this issue? 

Any hint would be highly appreciated!

**Comment by tholor** [comment]
Hey @TKueng, 

Sure, we are happy to help. Could you please provide a bit of additional context, so that we can narrow down the bug together:
 
- What versions of FARM and transformers are you using? 
- Do you know which version of FARM was used for training?
- What command and args do you use for loading the model? 
- If it's a local path: are you sure your model is stored at this location on your machine?  
- What are the file names in that folder?
- Can you run one of the default examples (e.g. [this](https://github.com/deepset-ai/FARM/blob/master/examples/doc_classification.py)) on your windows machine?

**Comment by TKueng** [comment]
Hello everyone 

Thank you so much for the fast answer. Your question already helped me to progress with my project. Just to answer your questions

- I had the newest version of farm 0.4.1 but switched it now to 0.3.0, which was the version the model was trained on. This allowed me to also load the Model configuaration. 

- I use the following command to load the model (but this is not a problem anymore): 
`    def __init__(self):
        self.model = Inferencer.load("C:\\Users\\tobia\\OneDrive\\Desktop\\arguebot_test\\Model")`

- The path of the model should definitely not be the problem. 

- But I think the files could be a problem. I have the following documents in the Model folder _.gitattributes_, _added_tokens.json_, _language_model.bin_, _language_model_config.json_, _prediction_head_0.bin_, _prediction_head_0_config.json_, _processor_config.json_, _special_tokens_map.json_, _tokenizer_config.json_, _vocab.txt_

- No when the model is trying to load the _language_model.bin_ file the following error occurs:

`2020-03-17 16:08:06 INFO     transformers.modeling_utils  - loading weights file C:\Users\tobia\OneDrive\Desktop\arguebot_test\Model\language_model.bin
Traceback (most recent call last):
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\endpoint.py", line 125, in <module>
    rasa_sdk.__main__.main()
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\__main__.py", line 29, in main
    main_from_args(cmdline_args)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\__main__.py", line 20, in main_from_args
    args.ssl_password,
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\endpoint.py", line 116, in run
    app = create_app(action_package_name, cors_origins=cors_origins)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\endpoint.py", line 68, in create_app
    executor.register_package(action_package_name)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\executor.py", line 222, in register_package
    self.register_action(action)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_sdk\executor.py", line 157, in register_action
    action = action()
  File "C:\Users\tobia\OneDrive\Desktop\arguebot_test\actions.py", line 15, in __init__
    self.model = Inferencer.load("C:\\Users\\tobia\\OneDrive\\Desktop\\arguebot_test\\Model")
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\infer.py", line 121, in load
    model = AdaptiveModel.load(load_dir, device)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\adaptive_model.py", line 89, in load
    language_model = LanguageModel.load(load_dir)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\language_model.py", line 86, in load
    language_model = cls.subclasses[config["name"]].load(pretrained_model_name_or_path)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\farm\modeling\language_model.py", line 249, in load
    bert.model = BertModel.from_pretrained(farm_lm_model, config=bert_config)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modeling_utils.py", line 345, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow`

Any thoughts on this issue? Would be so highly appreciated!!

**Comment by Timoeller** [comment]
About the pickle error:
Maybe you trained your model with a different torch version or a different python version than what you use now?

Would it be very difficult to re-train your model with most recent Farm and Transformers versions and your current setup? That way you do not land in version hell : )

**Comment by TKueng** [comment]
This is most probably since I personally have not trained the model, but a former student did so. I guess the easiest way would be to meet with the student and adjust the versions.

**Comment by TKueng** [comment]
Okay so I reached out to the former student (I think he was also in contact with you guys haha). I'm trying to retrain the model with the current versions of pytorch 1.4 and python 3.6. But can't git rid of the following error:

`from google.colab import drive`
`drive.mount('/content/gdrive')`

`import pandas as pd`
`import time`
`import numpy as np`
`import math`
`from sklearn.model_selection import train_test_split, KFold`

`!git clone https://github.com/deepset-ai/FARM.git`
`!pip install -r FARM/requirements.txt`
`!pip install FARM/`

`import torch`
`from farm.modeling.tokenization import BertTokenizer`
`from farm.data_handler.processor import TextClassificationProcessor`
`from farm.data_handler.data_silo import DataSilo`
`from farm.modeling.language_model import Bert`
`from farm.modeling.prediction_head import TextClassificationHead`
`from farm.modeling.adaptive_model import AdaptiveModel`
`from farm.modeling.optimization import initialize_optimizer`
`from farm.train import Trainer`
`from farm.data_handler.processor import NERProcessor`
`from farm.modeling.prediction_head import TokenClassificationHead`
`from farm.infer import Inferencer`
`from pprint import PrettyPrinter`

`#Load language model`
`MODEL_NAME_OR_PATH = "bert-base-german-cased"`
`language_model = Bert.load(MODEL_NAME_OR_PATH)`

`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`
`print("Devices available: {}".format(device))`

`from farm.experiment import run_experiment, load_experiments`
`final_model_path = F"/content/gdrive/My Drive/Colab Notebooks/final_model_premise_claim.json"`
`final_model = load_experiments(final_model_path)`

`run_experiment(final_model[0])`

**Comment by TKueng** [comment]
<img width="425" alt="Error" src="https://user-images.githubusercontent.com/61231500/77234518-6b305580-6baf-11ea-80cc-b9740f0c1af0.PNG">

**Comment by Timoeller** [comment]
Thanks for the detailed error description. Now we can narrow the issue down.

The error arises because your config for this experiment "final_model_premise_claim.json" is outdated and does not include the "use_amp" key.
We are aware that these breaking changes across FARM versions can be quite frustrating to the user.

I see two solutions:
1. Use the exact same setting of farm + pytorch that you used for running this experiment.
2. Update the config to our new style. You can find examples of how they should look like [here](https://github.com/deepset-ai/FARM/blob/master/experiments/text_classification/germEval18Fine_config.json)

**Comment by Timoeller** [comment]
Hey @TKueng did the proposed solutions resolve the issue on your end or do you need further assistance?
If it is fixed, please close the issue. Thanks.

**Comment by TKueng** [comment]
Hey @Timoeller 
Managed to retrain it and locally it works now just fine!
Just have one question now can the Inferencer load the model also in a github repository?
Because I tried to implement the chatbot now to my server and I did not actually work. So the question I have is, if I can just exchange this line of code 
`    def __init__(self):
        self.model = Inferencer.load("C:\\Users\\tobia\\OneDrive\\Desktop\\arguebot_test\\ModelTob")`

for this line of code:

`    def __init__(self):
        self.model = Inferencer.load("https://github.com/TKueng/argubotV1/ModelTob")`

**Comment by Timoeller** [comment]
Nice, happy you got it to work.

To your question:
No, the inferencer does not accept remote folders as of now. Though I think it could be a pretty useful feature. 
If you or any of your students implements this please add this to farm as well. 
You can also create a new issue, asking for assitance on this matter.

I am closing this now as resolved.
