### ISSUE TITLE
TextPairClassificationProcessor class misses "self.add_task()" method? Running the "text_pair_classification.py" example code

### ISSUE THREAD

**Issue by NicolasBenjamin** [deepset-ai/FARM#291]
Hi all,
first of all - thank you to the deepset team for open source this framework!  I'm a Master student at the Hasso-Plattner-Institute (HPI) and I am currently trying to get the example "text_pair_classification.py" running. 
However, I experienced some issues and kindly ask for any suggestions if this is a bug or I should use this example differently. Maybe you know more about this issue @brandenchan ?

Some prior info:
- I am using the newest farm version (0.4.1)
- As dummy data I am using a train.tsv file containing the three columns "text", "text_b", "label" with labels ["0", "1"]

When executing "text_pair_classification.py", the following error occurs:

```
Traceback (most recent call last):
  File "text_pair_classification.py", line 117, in <module>
    text_pair_classification()
  File "text_pair_classification.py", line 67, in text_pair_classification
    task_name="text_classification"),
  File "/home/nialde/FARM_framework/FARM/farm/data_handler/data_silo.py", line 441, in calculate_class_weights
    tensor_name = self.processor.tasks[task_name]["label_tensor_name"]
KeyError: 'text_classification'
```

In "text_pair_classification.py:43", we can find a reference to the RegressionProcessor class (instead of a reference to the TextPairClassificationProcessor): "#  We do not have a sample dataset for regression yet, add your own dataset to run the example".  

Following this hint and having a look into "/farm/data_handler/processor.py:1119",  I find the method „self.add_task()“ within the „_init_()“ method of the „RegressionProcessor“ class. If I add `self.add_task(name="text_classification", metric="mse", label_list=["0","1"], label_column_name="label", task_type="classification“)` into the "_init_()" method of the "TextPairClassificationProcessor" class, the error disappears and it seems to work. 

Do I assume true that the "self.add_task()" method was forgotten to add?

Cheers,
Nicolas

**Comment by brandenchan** [comment]
Hi Nicolas, thanks for your issue! And well done on figuring out the self.add_task() way of resolving this.

What we actually intended was for the Processor to be initialised with a metric param. That has now been fixed #294 . Also there is now a clearer error message when we are missing a task (330c14f6298d835a2d68e2b62fadd4753f264b86).

Thank you for pointing out the RegressionProcessor comment. The RegressionProcessor is not actually used in this script but we have also now fixed the comment!
