### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by binzhouchn** [deepset-ai/FARM#361]
hello,

when I do the tutorial classification 
model = trainer.train()
I got following error, could you help me out, thanks

SYSTEM:
ubuntu:16.04
torch:1.5.0
cuda version 10.1, with 4 gpu available.

---------------------------------------------------------------------------
```
StopIteration                             Traceback (most recent call last)
<ipython-input-15-bd7ca549ab20> in <module>
----> 1 model = trainer.train()

/usr/src/FARM/farm/train.py in train(self)
    249 
    250                 # Forward pass through model
--> 251                 logits = self.model.forward(**batch)
    252                 per_sample_loss = self.model.logits_to_loss(logits=logits, global_step=self.global_step, **batch)
    253 

/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    153             return self.module(*inputs[0], **kwargs[0])
    154         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 155         outputs = self.parallel_apply(replicas, inputs, kwargs)
    156         return self.gather(outputs, self.output_device)
    157 

/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    163 
    164     def parallel_apply(self, replicas, inputs, kwargs):
--> 165         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    166 
    167     def gather(self, outputs, output_device):

/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     83         output = results[i]
     84         if isinstance(output, ExceptionWrapper):
---> 85             output.reraise()
     86         outputs.append(output)
     87     return outputs

/opt/conda/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    393             # (https://bugs.python.org/issue2651), so we work around it.
    394             msg = KeyErrorMessage(msg)
--> 395         raise self.exc_type(msg)

StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/FARM/farm/modeling/adaptive_model.py", line 401, in forward
    sequence_output, pooled_output = self.forward_lm(**kwargs)
  File "/usr/src/FARM/farm/modeling/adaptive_model.py", line 443, in forward_lm
    sequence_output, pooled_output = self.language_model(**kwargs, output_all_encoded_layers=False)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/FARM/farm/modeling/language_model.py", line 420, in forward
    attention_mask=padding_mask,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_bert.py", line 734, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration
```

**Comment by Timoeller** [comment]
Hey @binzhouchn sorry for the late reply. 
This sounds like a version issue to me. 
So could you try either 
- running the code with pytorch 1.4.0 installed
- upgrading cuda to 10.2 (I though pytorch 1.5.0 requires cuda 10.2 anyways?)

Hope that helps

**Comment by Timoeller** [comment]
Closing this now, feel free to reopen if the issue persists
