### ISSUE TITLE
Support for CamemBERT-like model types

### ISSUE THREAD

**Issue by scheiblr** [deepset-ai/FARM#386]
It would be nice to be able to use CamemBERT like models in the experiment environment. UmBERTo, the italien model is also like that.

**Describe the solution you'd like**
Please add it to the experiment framework :)

**Additional context**
Information about CamemBERT: https://huggingface.co/transformers/model_doc/camembert.html

**Comment by Timoeller** [comment]
Hey @scheiblr having camembert models in FARM would be nice!

Do you want to create a PR with proposed changes and we help you implementing it?

**Comment by Timoeller** [comment]
We have added CamemBERT in #396 
@scheiblr could you test and verify that the model integration worked with your use case?

**Comment by Timoeller** [comment]
Hey @scheiblr could you verify that camembert works for your use case on our feature branch?

**Comment by scheiblr** [comment]
Sorry, I was out of office until yesterday. I'm currently checking it.

**Comment by scheiblr** [comment]
Unfortunately, squad20 crashes when trying camembert-like models (e.g. camembert/camembert-base).

**Comment by Timoeller** [comment]
We have tested the code and on our side it works.

Could you give detailed code and error information, so we might be able to replicate?

**Comment by scheiblr** [comment]
I just tried to run the following test-json with the experiments platform:
[squad20_config.zip](https://github.com/deepset-ai/FARM/files/4792377/squad20_config.zip)



The error was:
```
Preprocessing Dataset data/squad20/train-v2.0.json:   0%|                                                                             | 0/19035 [00:03<?, ? Dicts/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/scheiblr/anaconda3/envs/farm/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/data_silo.py", line 124, in _dataset_from_chunk
    dataset = processor.dataset_from_dicts(dicts=dicts, indices=indices)
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/processor.py", line 1070, in dataset_from_dicts
    self._featurize_samples()
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/processor.py", line 295, in _featurize_samples
    sample.features = self._sample_to_features(sample=sample)
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/processor.py", line 1171, in _sample_to_features
    max_seq_len=self.max_seq_len)
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/input_features.py", line 362, in sample_to_features_qa
    seq_2_start_t = segment_ids.index(1)
ValueError: 1 is not in list
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "experiments/run_experiments_from_config.py", line 25, in <module>
    run_experiment(experiment)
  File "/home/scheiblr/Spielewiese/FARM/farm/experiment.py", line 75, in run_experiment
    distributed=distributed,
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/data_silo.py", line 105, in __init__
    self._load_data()
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/data_silo.py", line 207, in _load_data
    self.data["train"], self.tensor_names = self._get_dataset(train_file)
  File "/home/scheiblr/Spielewiese/FARM/farm/data_handler/data_silo.py", line 176, in _get_dataset
    for dataset, tensor_names in results:
  File "/home/scheiblr/anaconda3/envs/farm/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: 1 is not in list
```

I'm currently checked out in the feature branch (support_camembert)

**Comment by Timoeller** [comment]
For me it works with your config (without local MLflow).
Could you check out and work on the current master branch, please? Camembert support is in there.
