### ISSUE TITLE
QA inference breaks on large dataset

### ISSUE THREAD

**Issue by Timoeller** [deepset-ai/FARM#454]
**Describe the bug**
QA inference failing on very large dataset

**Error message**
Inferencing Samples: 0 Batches [00:00, ? Batches/s]Traceback (most recent call last):
  File "question_answering_inference.py", line 89, in <module>
    question_answering()
  File "question_answering_inference.py", line 34, in question_answering
    result = model.inference_from_file(file=filename, return_json=False, multiprocessing_chunksize=1)
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 645, in inference_from_file
    multiprocessing_chunksize=multiprocessing_chunksize, streaming=streaming)
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 345, in inference_from_file
    streaming=streaming,
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 637, in inference_from_dicts
    multiprocessing_chunksize=multiprocessing_chunksize, streaming=streaming)
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 418, in inference_from_dicts
    return list(predictions)
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 489, in _inference_with_multiprocessing
    dataset, tensor_names, baskets
  File "/home/ubuntu/pycharm/timosyncNEW/farm/infer.py", line 576, in _get_predictions_and_aggregate
    for i, batch in enumerate(tqdm(data_loader, desc=f"Inferencing Samples", unit=" Batches", disable=self.disable_tqdm)):
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1060, in __iter__
    for obj in iterable:
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 62, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

**Additional context**
I suspect this has to do with one whole chunk in multiprocessing not being transformed correctly. We should remove empty datasets before sending them to _get_predictions_and_aggregate.

**Comment by jamontol** [comment]
I have the same problem running inference_from_file on Kubeflow with FARM 0.4.7, but I can't reproduce the same error on Colab

predictions_json = model.inference_from_file(file=json_eval)
  File "/usr/local/lib/python3.7/site-packages/farm/infer.py", line 379, in inference_from_file
    streaming=streaming,
  File "/usr/local/lib/python3.7/site-packages/farm/infer.py", line 456, in inference_from_dicts
    return list(predictions)
  File "/usr/local/lib/python3.7/site-packages/farm/infer.py", line 531, in _inference_with_multiprocessing
    dataset, tensor_names, baskets
  File "/usr/local/lib/python3.7/site-packages/farm/infer.py", line 610, in _get_predictions_and_aggregate
    for i, batch in enumerate(tqdm(data_loader, desc=f"Inferencing Samples", unit=" Batches", disable=self.disable_tqdm)):
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 402, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 62, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

**Comment by Timoeller** [comment]
Strange that this error pops up, I thought this happens in very special cases only.

How many cpu cores are on your Kubeflow instance?
When working in colab, can you tell if many QA pairs are dismissed and not loaded for modelling?

**Comment by jamontol** [comment]
> Strange that this error pops up, I thought this happens in very special cases only.
> 
> How many cpu cores are on your Kubeflow instance?
> When working in colab, can you tell if many QA pairs are dismissed and not loaded for modelling?

The Kubeflow node has 3 parallel workers, in Colab
I realized that I can fix the problem in Kubeflow removing empty qas when splitting squad dataset ( "qas": []). But I can figure out why this is not happening in Colab. Both experiments are running without GPU

**Comment by Timoeller** [comment]
Thanks for the additional infos. The devil is surprisingly in the details of our framework : ) 

When you have 7 workers the data is chunked into smaller parts than when you have only 2 (as in colab). I suspect one of these chunks contained only empty qas lists and therefor a whole chunk does not contain any QA pairs. Do you have a lot of empty lists? And how did you create the annotations?
