### ISSUE TITLE
Data Handler dataset creation fails if features are not computed for some baskets 

### ISSUE THREAD

**Issue by ftesser** [deepset-ai/FARM#457]
**Describe the bug**
method `farm.data_handler.processor.Processor._create_dataset` fails if features are not computed for some basket.
The specific case of the error message below is the training of SQuAD question answering, the context of the issue is the following:
 * the input SQuAD data contains some "errors" (some misalignment between answer text and selected text in the context);
 * this misalignment cause the exclusion of the features computation the `_featurize_samples` method (see the try-except):  https://github.com/deepset-ai/FARM/blob/b8b59c4c8fb98b92f24f0e92f9e4f44db5549323/farm/data_handler/processor.py#L295
 * finally in `_create_dataset` when the basket has no feature  `features_flat.extend`  https://github.com/deepset-ai/FARM/blob/b8b59c4c8fb98b92f24f0e92f9e4f44db5549323/farm/data_handler/processor.py#L308
gives the error message reported below.

**Error message**
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/data_silo.py", line 124, in _dataset_from_chunk
    dataset = processor.dataset_from_dicts(dicts=dicts, indices=indices)
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/processor.py", line 1144, in dataset_from_dicts
    dataset, tensor_names = self._create_dataset(keep_baskets=False)
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/processor.py", line 308, in _create_dataset
    features_flat.extend(sample.features)
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fabio/src/git_repositories/DocumentFeaturesIdentificator/bin/farm_qa", line 10, in <module>
    farm_qa.main()
  File "/home/fabio/src/git_repositories/DocumentFeaturesIdentificator/bin/../documentfeaturesidentificator/farm_utils/farm_qa.py", line 211, in main
    options.func(options)
  File "/home/fabio/src/git_repositories/DocumentFeaturesIdentificator/bin/../documentfeaturesidentificator/farm_utils/farm_qa.py", line 107, in train_general_purpose
    train_mock(options, base_lm_model, out_model_basename, train_filename, dev_filename, test_filename)
  File "/home/fabio/src/git_repositories/DocumentFeaturesIdentificator/bin/../documentfeaturesidentificator/farm_utils/farm_qa.py", line 146, in train_mock
    question_answering(options_mock)
  File "/home/fabio/src/git_repositories/DocumentFeaturesIdentificator/bin/../documentfeaturesidentificator/farm_utils/question_answering.py", line 79, in question_answering
    data_silo = DataSilo(processor=processor, batch_size=batch_size, distributed=False)
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/data_silo.py", line 105, in __init__
    self._load_data()
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/data_silo.py", line 207, in _load_data
    self.data["train"], self.tensor_names = self._get_dataset(train_file)
  File "/home/fabio/src/git_repositories/FARM/farm/data_handler/data_silo.py", line 176, in _get_dataset
    for dataset, tensor_names in results:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**
Logging the errors (perhaps with more information) and automatically exclude the basket with errors from the dataset.

**Additional context**
Add any other context about the problem here, like type of downstream task, part of  etc.. 

**To Reproduce**
Manually corrupt squad data test (e.g.: add a character in an answer in train-v2.0.json) and then run examples/question_answering.py 

**System:**
 - OS: Linux
 - GPU/CPU: CPU
 - FARM version: 0.4.6

**Comment by ftesser** [comment]
In order to automatically remove the baskets without features from the dataset I have two proposals: but I am not sure which one is better (or if they are OK with the design of the data pipeline):

1. remove the baskets without features directly on `_featurize_samples`;
2. remove the baskets without features on `_create_dataset`.

If you think one of these two approaches  can be ok I can make a PR.

**Comment by brandenchan** [comment]
Thank you for pointing this out and working on this! Yes I think removing baskets without features is the right move here. I would just opt for 2. since preprocessing could fail at _init_samples_in_baskets() or _featurize_samples(). Removing baskets at _create_dataset() would be able to deal with both cases

**Comment by Timoeller** [comment]
Issue seems related to #454

**Comment by ftesser** [comment]
Ah OK, if this is related to this other issue probably I have not the necessary global overview of the project to fix both (perhaps fixing #454 will result in the fix of this issue as well?)

Anyway, if you think should be helpful, I can make a PR for my original solution 2.

**Comment by Timoeller** [comment]
Lets move forward step by step. 
I think the issue you raised is more localized and easier to tackle. So we should proceed with your PR first.

Maybe it's even the other way around and #454 is solved by your PR ;)

**Comment by ftesser** [comment]
Ok @Timoeller :)
@brandenchan this last PR is removing baskets at _create_dataset().

**Comment by ftesser** [comment]
Hi all, with this last PR the train of the "misaligned train squad file" ends successfully.
However if I try to predict a "misaligned test squad file" with the model:
```python
model = QAInferencer.load(save_dir, task_type='question_answering')
result = model.inference_from_file(file=test_filename)
```
the misaligned basket are removed also in case (in the inference case this could be avoided as we just use the context and the questions but this is acceptable as I suppose the same squad data processor is used for train and inference): 
```log
07/14/2020 17:48:14 - ERROR - farm.data_handler.processor -   Basket id: id_internal: 1999-0, id_external: 572881704b864d1900164a50
07/14/2020 17:48:14 - ERROR - farm.data_handler.processor -   Error message: Answer using start/end indices is 'Quattro' while gold label text is 'quattro'
07/14/2020 17:48:14 - WARNING - farm.data_handler.processor -   Removing the following baskets because of errors in computing features:
07/14/2020 17:48:14 - WARNING - farm.data_handler.processor -   Basket id: id_internal: 1999-0, id_external: 572881704b864d1900164a50
```

but then I obtained the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 645, in inference_from_file
    multiprocessing_chunksize=multiprocessing_chunksize, streaming=streaming)
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 345, in inference_from_file
    streaming=streaming,
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 637, in inference_from_dicts
    multiprocessing_chunksize=multiprocessing_chunksize, streaming=streaming)
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 418, in inference_from_dicts
    return list(predictions)
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 489, in _inference_with_multiprocessing
    dataset, tensor_names, baskets
  File "/home/test/.local/lib/python3.7/site-packages/farm/infer.py", line 600, in _get_predictions_and_aggregate
    baskets=baskets)
  File "/home/test/.local/lib/python3.7/site-packages/farm/modeling/adaptive_model.py", line 104, in formatted_preds
    preds = head.formatted_preds(logits=logits_for_head, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/farm/modeling/prediction_head.py", line 1218, in formatted_preds
    preds_d = self.aggregate_preds(preds, passage_start_t, ids, seq_2_start_t)
  File "/home/test/.local/lib/python3.7/site-packages/farm/modeling/prediction_head.py", line 1310, in aggregate_preds
    pred_d = self.pred_to_doc_idxs(preds[sample_idx], curr_passage_start_t)
  File "/home/test/.local/lib/python3.7/site-packages/farm/modeling/prediction_head.py", line 1447, in pred_to_doc_idxs
    assert start >= 0
AssertionError
```

Perhaps some misalignment between baskets (some baskets has been removed) in the aggregations phase?

**Comment by brandenchan** [comment]
Hmmm this is something to do with the calculation of document indexes. Is there any chance you can send us the input data that you're working with so that we can try to replicate this on our side?

**Comment by ftesser** [comment]
Hello @brandenchan, I have followed your suggestion for this last PR.
I tested the new code with my "bugged data" and now, I do not obtain any errors in both train and inference.
So probably there was some misalignment between baskets.

Regarding the data, if you like to investigate more, I can send you some examples that failed before this PR.

**Comment by brandenchan** [comment]
Ok great! I think that #471 is certainly an improvement on the error handling front. I also think misalignment between baskets is a likely reason why you were getting the index error so I don't think its necessary to investigate that right now. Thanks for your work on this!
