### ISSUE TITLE
legacy multi-label data representation in eval metrics

### ISSUE THREAD

**Issue by djstrong** [deepset-ai/FARM#498]
**Error message**
Traceback (most recent call last):
  File "ner.py", line 115, in <module>
    ner()
  File "ner.py", line 94, in ner
    trainer.train()
  File "/farm-train/FARM/farm/train.py", line 306, in train
    result = evaluator_dev.eval(self.model)
  File "/farm-train/FARM/farm/eval.py", line 104, in eval
    compute_metrics(metric=head.metric, preds=preds_all[head_num], labels=label_all[head_num]
  File "/farm-train/FARM/farm/evaluation/metrics.py", line 79, in compute_metrics
    return acc_and_f1(preds, labels)
  File "/farm-train/FARM/farm/evaluation/metrics.py", line 55, in acc_and_f1
    f1 = f1_score(y_true=labels, y_pred=preds)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1047, in f1_score
    zero_division=zero_division)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1175, in fbeta_score
    zero_division=zero_division)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1434, in precision_recall_fscore_support
    pos_label)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1250, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 82, in _check_targets
    type_true = type_of_target(y_true)
  File "/farm-train/venv/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 263, in type_of_target
    raise ValueError('You appear to be using a legacy multi-label data'
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.

**To Reproduce**
Run ner example with metric changed to `acc_f1` (as I need per token accuracy).

**System:**
scikit-learn 0.23.2

**Comment by tholor** [comment]
Thanks for reporting this bug @djstrong . 

Solution seems straightforward: https://stackoverflow.com/questions/34213199/scikit-learn-multilabel-classification-valueerror-you-appear-to-be-using-a-leg

Would you be interested in creating a PR? Otherwise, we will tackle it with our team.

**Comment by djstrong** [comment]
Actually I have used seqeval.metrics.acc_score, which works properly for sequences.

`MultiLabelBinarizer` solution would be wrong.

So, you should keep separate metrics for token classification and text classification or create more universal.

**Comment by tholor** [comment]
Ok, we will have a look at it. As there are several workarounds (older sklearn version or acc_score metrics via register_metrics), this will have lower priority for us though.
