### ISSUE TITLE
farm-inference-api crash when attempting to load own model

### ISSUE THREAD

**Issue by DieseKartoffel** [deepset-ai/FARM#751]
**Describe the bug**
I finetuned a model using FARM and saved it as described in the examples. After placing it in the "saved_models" dir, `docker-compose up` throws an exception and the inference-api does not start. The web-ui will display a white screen. When the "saved_models" dir is empty, inference-api  and web-ui are working fine.

**Error message**
```
>docker compose up
[+] Running 2/2
 - Container farm_inference-ui_1   Recreated                                                                                            0.1s
 - Container farm_inference-api_1  Recreated                                                                                            0.2s
Attaching to inference-api_1, inference-ui_1
inference-api_1  |  * Serving Flask app "farm.inference_rest_api"
inference-api_1  |  * Environment: production
inference-api_1  |    WARNING: This is a development server. Do not use it in a production deployment.
inference-api_1  |    Use a production WSGI server instead.
inference-api_1  |  * Debug mode: off
inference-api_1  | 04/23/2021 06:51:42 - INFO - transformers.file_utils -   PyTorch version 1.4.0 available.
inference-api_1  | 04/23/2021 06:51:43 - INFO - farm.utils -   device: cpu n_gpu: 0, distributed training: False, automatic mixed precision training: None
inference-api_1  | 04/23/2021 06:51:43 - INFO - transformers.modeling_utils -   loading weights file saved_models/bert-base-uncased-fakenews/language_model.bin from cache at saved_models/bert-base-uncased-fakenews/language_model.bin
inference-api_1  | Traceback (most recent call last):
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/transformers/modeling_utils.py", line 516, in from_pretrained
inference-api_1  |     state_dict = torch.load(resolved_archive_file, map_location="cpu")
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
inference-api_1  |     with _open_zipfile_reader(f) as opened_zipfile:
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
inference-api_1  |     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
inference-api_1  | RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
inference-api_1  | frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f93c9d48193 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
inference-api_1  | frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f93cd0d89eb in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
inference-api_1  | frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f93cd0d9c04 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
inference-api_1  | frame #3: <unknown function> + 0x6c6536 (0x7f94155a3536 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
inference-api_1  | frame #4: <unknown function> + 0x295a74 (0x7f9415172a74 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
inference-api_1  | <omitting python frames>
inference-api_1  |
inference-api_1  |
inference-api_1  | During handling of the above exception, another exception occurred:
inference-api_1  |
inference-api_1  | Traceback (most recent call last):
inference-api_1  |   File "/usr/local/bin/flask", line 8, in <module>
inference-api_1  |     sys.exit(main())
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 966, in main
inference-api_1  |     cli.main(prog_name="python -m flask" if as_module else None)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
inference-api_1  |     return super(FlaskGroup, self).main(*args, **kwargs)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
inference-api_1  |     rv = self.invoke(ctx)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
inference-api_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
inference-api_1  |     return ctx.invoke(self.callback, **ctx.params)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
inference-api_1  |     return callback(*args, **kwargs)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
inference-api_1  |     return ctx.invoke(f, obj, *args, **kwargs)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
inference-api_1  |     return callback(*args, **kwargs)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command
inference-api_1  |     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__
inference-api_1  |     self._load_unlocked()
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
inference-api_1  |     self._app = rv = self.loader()
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
inference-api_1  |     app = locate_app(self, import_name, name)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
inference-api_1  |     __import__(module_name)
inference-api_1  |   File "/home/user/farm/inference_rest_api.py", line 30, in <module>
inference-api_1  |     INFERENCERS[idx + 1] = Inferencer.load(str(model_dir))
inference-api_1  |   File "/home/user/farm/infer.py", line 160, in load
inference-api_1  |     model = BaseAdaptiveModel.load(load_dir=model_name_or_path, device=device, strict=strict)
inference-api_1  |   File "/home/user/farm/modeling/adaptive_model.py", line 53, in load
inference-api_1  |     model = cls.subclasses["AdaptiveModel"].load(**kwargs)
inference-api_1  |   File "/home/user/farm/modeling/adaptive_model.py", line 271, in load
inference-api_1  |     language_model = LanguageModel.load(load_dir)
inference-api_1  |   File "/home/user/farm/modeling/language_model.py", line 113, in load
inference-api_1  |     language_model = cls.subclasses[config["name"]].load(pretrained_model_name_or_path)
inference-api_1  |   File "/home/user/farm/modeling/language_model.py", line 359, in load
inference-api_1  |     bert.model = BertModel.from_pretrained(farm_lm_model, config=bert_config, **kwargs)
inference-api_1  |   File "/usr/local/lib/python3.7/site-packages/transformers/modeling_utils.py", line 519, in from_pretrained
inference-api_1  |     "Unable to load weights from pytorch checkpoint file. "
inference-api_1  | OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
inference-api_1 exited with code 1
```

**Expected behavior**
Expected the FARM UI to start up and load my model. If the model file is actually corrupted or incompatible, the API server should not crash but show a error message to help the user and boot up anyway. Alternativley, the UI itself could show the error when attempting to select the model.

**Additional context**
I trained a model on hate-speech detection using my own dataset. I placed a copy of the code I used here:
https://github.com/DieseKartoffel/my-fileshare-repo/blob/master/finetune.ipynb

**To Reproduce**
I am using torch 1.8.1+cu111. I tested loading the model with torch 1.7.1+cpu and got the same error. Otherwise I am using a fresh install of FARM requirements.txt in an empty conda environment. I installed from the latest source, not pip. Finetune a model as described in the notebook and place it in the ./saved_models dir to reproduce.

**System:**
 - OS: Windows 10
 - GPU/CPU: Nvidia GTX 1080 / Intel i5-4690k
 - FARM version: 0.7.1

/Really enjoying the library by the way! Thank you for creating it :)

**Comment by Timoeller** [comment]
Hey sorry for the late reply. Really appreciate the effort you put into creating the issue. 

>  File "/home/user/farm/inference_rest_api.py", line 30, in <module>
inference-api_1  |     INFERENCERS[idx + 1] = Inferencer.load(str(model_dir))


It is strange that loading the model in your example notebook works but within the inference api as seen in the code snippet above does not. Could you post the configs that are saved in your custom model please, maybe there is an error?


 I have also assigned our data engineer to this issue since he was mainly involved in creating the rest api but he is very busy currently in other parts of our code. So please be a bit patient.

**Comment by DieseKartoffel** [comment]
Thanks for looking into it! And don't worry, this is not high priority for me either. I mainly just wanted to let you know about it.
I uploaded the config files [here](https://github.com/DieseKartoffel/my-fileshare-repo).
