### ISSUE TITLE
CoNLL-2003: index out of range

### ISSUE THREAD

**Issue by stefan-it** [deepset-ai/FARM#78]
Hi :)

I wanted to train a NER model on the CoNLL-2003 dataset (I only changed the path to the dataset in the configuration file).:

```python
from farm.experiment import run_experiment, load_experiments 
experiments = load_experiments("experiments/ner/conll2003_de_config.json")
run_experiment(experiments[0])
```

Then the following error message appears:

```bash
09/03/2019 19:03:58 - INFO - farm.utils -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
09/03/2019 19:03:58 - INFO - pytorch_transformers.tokenization_utils -   loading file https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt from cache at /root/.cache/torch/pytorch_transformers/da299cdd121a3d71e1626f2908dda0d02658f42e925a3d6abd8273ec08cf41a6.2a48e6c60dcdb582effb718237ce5894652e3b4abb94f0a4d9a857b70333308d
09/03/2019 19:03:58 - INFO - farm.data_handler.data_silo -   
Loading data into the data silo ... 
              ______
               |o  |   !
   __          |:`_|---'-.
  |__|______.-/ _ \-----.|       
 (o)(o)------'\ _ /     ( )      
 
09/03/2019 19:03:58 - INFO - farm.data_handler.data_silo -   Loading train set from: /root/.flair/datasets/conll_03_german/train.txt 
09/03/2019 19:03:59 - INFO - farm.data_handler.processor -   Got ya 12 parallel workers to fill the baskets with samples (chunksize = 1000)...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12152/12152 [00:04<00:00, 2728.79it/s]
09/03/2019 19:04:04 - INFO - farm.data_handler.processor -   Got ya 12 parallel workers to featurize samples in baskets (chunksize = 1000) ...
  0%|                                                                                                                          | 0/12152 [00:00<?, ?it/s]---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/FARM/farm/data_handler/processor.py", line 367, in _multiproc_featurize
    all_features.append(cls._sample_to_features(sample=sample))
  File "/mnt/FARM/farm/data_handler/processor.py", line 665, in _sample_to_features
    tokenizer=cls.tokenizer,
  File "/mnt/FARM/farm/data_handler/input_features.py", line 185, in samples_to_features_ner
    labels_token = expand_labels(labels_word, initial_mask, non_initial_token)
  File "/mnt/FARM/farm/data_handler/utils.py", line 214, in expand_labels
    labels_token.append(labels_word[word_index])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-3-386307ddc5b9> in <module>
----> 1 run_experiment(experiments[0])

/mnt/FARM/farm/experiment.py in run_experiment(args)
     85         processor=processor,
     86         batch_size=args.parameter.batch_size,
---> 87         distributed=distributed,
     88     )
     89 

/mnt/FARM/farm/data_handler/data_silo.py in __init__(self, processor, batch_size, distributed)
     38         self.batch_size = batch_size
     39         self.class_weights = None
---> 40         self._load_data()
     41 
     42     def _load_data(self):

/mnt/FARM/farm/data_handler/data_silo.py in _load_data(self)
     46         train_file = os.path.join(self.processor.data_dir, self.processor.train_filename)
     47         logger.info("Loading train set from: {} ".format(train_file))
---> 48         self.data["train"], self.tensor_names = self.processor.dataset_from_file(train_file)
     49 
     50         # dev data

/mnt/FARM/farm/data_handler/processor.py in dataset_from_file(self, file, log_time)
    396             c = time.time()
    397             MlLogger.log_metrics(metrics={"t_init_samples": (c - b) / 60}, step=0)
--> 398             self._featurize_samples()
    399             d = time.time()
    400             MlLogger.log_metrics(metrics={"t_featurize_samples": (d - c) / 60}, step=0)

/mnt/FARM/farm/data_handler/processor.py in _featurize_samples(self)
    345 
    346                 for basket_features, basket in tqdm(
--> 347                         zip(all_features_gen, self.baskets), total=len(self.baskets)
    348                 ):
    349                     for f, s in zip(basket_features, basket.samples):

/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py in __iter__(self)
   1058                 """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1059 
-> 1060             for obj in iterable:
   1061                 yield obj
   1062                 # Update and possibly print the progressbar.

/usr/lib/python3.6/multiprocessing/pool.py in <genexpr>(.0)
    318                     result._set_length
    319                 ))
--> 320             return (item for chunk in result for item in chunk)
    321 
    322     def imap_unordered(self, func, iterable, chunksize=1):

/usr/lib/python3.6/multiprocessing/pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

IndexError: list index out of range
```

Could you help me with that? I used the latest *FARM* version from `master` branch. Thanks :heart:

**Comment by Timoeller** [comment]
Hey, 
that does look like the data is not in the right format. You are loading our version of conll 2003 or the version linked on the flair page, I think they link [this](https://www.clips.uantwerpen.be/conll2003/ner/) page? It might be that this dataset is different to what we use. Could you try running the experiment with the default path? The default path should be empty, so it downloads the dataset we use.

**Comment by stefan-it** [comment]
Thanks for your help! I tried using the default path and training is now working :+1: Indeed, the data format is different (compared to the format that we use in flair 😅) So I'll close that issue here 🤗
