### ISSUE TITLE
Threading Error upon building Data Silo

### ISSUE THREAD

**Issue by FelineWeise** [deepset-ai/FARM#90]
Upon loading the DataSilo, which would theoretically call the functions in previously created Processor object to generate the datasets, I keep running into a threading error without being given any useful information regarding the interplay between the threading.py module and FARM (see complete stacktrace below).

**Error message**:
09/16/2019 15:15:59 - INFO - farm.data_handler.data_silo -   
Loading data into the data silo ... 
              ______
               |o  |   !
   __          |:`_|---'-.
  |__|______.-/ _ \-----.|       
 (o)(o)------'\ _ /     ( )      
 
09/16/2019 15:15:59 - INFO - farm.data_handler.data_silo -   Loading train set from: data_train.tsv 

09/16/2019 15:15:59 - INFO - farm.data_handler.processor -   Got ya 2 parallel workers to fill the baskets with samples (chunksize = 1000)...
Exception ignored in: <function _after_fork at 0x7fe36e789170>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1374, in _after_fork
    assert len(_active) == 1
AssertionError: 
Exception ignored in: <function _after_fork at 0x7fe36e789170>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1374, in _after_fork
    assert len(_active) == 1
AssertionError: 

**Expected behavior**
I expected that a DataLoader object would be returned, which will later be passed on to the model Trainer object. 

**To Reproduce**
Screenshot of file heads and Code snippet needed to reproduce attached.

**System:**
 - OS: Linux Mint 19.1
 - GPU/CPU: cpu
- FARM version: farm-0.2.0

![head_data_test](https://user-images.githubusercontent.com/49808834/64964352-34ddea80-d89b-11e9-9781-d96075cf64ad.png)
![head_data_train](https://user-images.githubusercontent.com/49808834/64964353-34ddea80-d89b-11e9-8186-185578c4c982.png)
[FARM_ErrorToReproduce.pdf](https://github.com/deepset-ai/FARM/files/3616584/FARM_ErrorToReproduce.pdf)

**Comment by tanaysoni** [comment]
Hi @FelineWeise, thank you for reporting the issue.

Could you check if the supplied example `examples/doc_classification.py` runs without an error?

**Comment by FelineWeise** [comment]
**Hey @tanaysoni, many thanks for your response. 

Indeed, removing eventlet.patcher.monkey_patch() solves the threading issue. However, another error occurs upon calling the DataSilo object:**  

09/16/2019 17:56:29 - INFO - pytorch_transformers.tokenization_utils -   loading file https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt from cache at /home/f_weise/.cache/torch/pytorch_transformers/da299cdd121a3d71e1626f2908dda0d02658f42e925a3d6abd8273ec08cf41a6.2a48e6c60dcdb582effb718237ce5894652e3b4abb94f0a4d9a857b70333308d
09/16/2019 17:56:30 - INFO - farm.data_handler.data_silo -   
Loading data into the data silo ... 
              ______
               |o  |   !
   __          |:`_|---'-.
  |__|______.-/ _ \-----.|       
 (o)(o)------'\ _ /     ( )      
 
09/16/2019 17:56:30 - INFO - farm.data_handler.data_silo -   Loading train set from: /home/f_weise/projects/adup-watchdog/src/scripts/data_train.tsv 
09/16/2019 17:56:31 - INFO - farm.data_handler.processor -   Got ya 3 parallel workers to fill the baskets with samples (chunksize = 1000)...
  0%|          | 0/3134 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/processor.py", line 307, in _multiproc_sample
    samples = cls._dict_to_samples(dict=basket.raw, all_dicts=all_dicts)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/processor.py", line 477, in _dict_to_samples
    tokenized = tokenize_with_metadata(dict["text"], cls.tokenizer, cls.max_seq_len)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/modeling/tokenization.py", line 164, in tokenize_with_metadata
    words = text.split(" ")
AttributeError: 'float' object has no attribute 'split'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/f_weise/projects/adup-watchdog/src/scripts/BertBaseCased.py", line 79, in <module>
    data_silo = DataSilo(processor=processor,batch_size= 15)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 39, in __init__
    self._load_data()
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 47, in _load_data
    self.data["train"], self.tensor_names = self.processor.dataset_from_file(train_file)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/processor.py", line 363, in dataset_from_file
    self._init_samples_in_baskets()
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/processor.py", line 301, in _init_samples_in_baskets
    zip(samples, self.baskets), total=len(self.baskets)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1060, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'float' object has no attribute 'split'
  0%|          | 0/3134 [00:16<?, ?it/s]



**When I run examples/doc_classification.py I'm running into another error:** 

09/16/2019 17:37:10 - INFO - pytorch_transformers.tokenization_utils -   loading file https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt from cache at /home/f_weise/.cache/torch/pytorch_transformers/da299cdd121a3d71e1626f2908dda0d02658f42e925a3d6abd8273ec08cf41a6.2a48e6c60dcdb582effb718237ce5894652e3b4abb94f0a4d9a857b70333308d
Traceback (most recent call last):
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/f_weise/projects/adup-watchdog/src/scripts/FARMexamples_docclassification.py", line 49, in <module>
    source_field="coarse_label"
TypeError: __init__() missing 1 required positional argument: 'label_list'


**In an attempt to respond to this error message by passing label_list to the TextClassificationProcessor** (processor = TextClassificationProcessor(tokenizer=tokenizer,
                                        max_seq_len=128,
                                        data_dir="../data/germeval18",
                                        labels = ["OTHER", "OFFENSE"],
                                        label_list=label_list,
                                        metric=metric,
                                        source_field="coarse_label",
                                        label_dtype= torch.long,
                                        columns = ['text', 'coarse_label']
                                        )) **another error message is thrown:** 

Traceback (most recent call last):
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/f_weise/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.5728.105/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/f_weise/projects/adup-watchdog/src/scripts/FARMexamples_docclassification.py", line 67, in <module>
    batch_size=batch_size)
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 39, in __init__
    self._load_data()
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 73, in _load_data
    self._calculate_class_weights(self.data["train"])
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 180, in _calculate_class_weights
    labels = [x[3].item() for x in dataset]
  File "/home/f_weise/projects/adup-watchdog/.venv/lib/python3.7/site-packages/farm/data_handler/data_silo.py", line 180, in <listcomp>
    labels = [x[3].item() for x in dataset]
IndexError: tuple index out of range


Thanks for your great support! 
I hope you have some additional advice on how to fix any of the above. 

Thanky ou very much in advance!!!

**Comment by tanaysoni** [comment]
The first issue has been fixed by #67.  

For the second, it seems you're running a recent version of the example against an earlier FARM release.

Reinstalling FARM using the latest master branch with `pip install -e .` should resolve both issues.
